### ISSUE TITLE
Text in editionView on each of reference_many doesn´t show

### ISSUE THREAD

**Issue by HenrikMilefors** [marmelab/ng-admin#634]
I'm having trouble loading an editionView on a field of type reference_many. The inner label for each reference doesn´t show. Adding new works fine and they show up with text. My configuration worked fine in 0.7 and have have doublechecked the configuration according to NG Admin Demo and see no difference. Did I miss something?

![ngadmin_reference_many](https://cloud.githubusercontent.com/assets/9380089/9573466/237db65a-4fbd-11e5-8ca0-f6ca1c2236fe.png)

All the best
Henrik

**Comment by ace-han** [comment]
Hi, I came across the same problem, any update here?

**Comment by ace-han** [comment]
Sorry, my bad. I was changing the same field type from `reference` to `reference_many`
My is okay now.

**Comment by HenrikMilefors** [comment]
Simple solution to this. The API needs to have and endpoint returning single entity by entity ID. This wasn´t needed in earlier version.

**Comment by fzaninotto** [comment]
There was a regression with `reference.singleApiCall()`, which was fixed a couple days ago. Could you check that the master branch has your bug fixed?

**Comment by ajarbol** [comment]
+1 I'm also having trouble with this. The server response is:
<img width="319" alt="screen shot 2016-02-11 at 2 22 57 am" src="https://cloud.githubusercontent.com/assets/4655439/12967381/68321bf4-d066-11e5-8189-0228200d73a9.png">
And I'm using the simple field:
```        	
nga.field('features', 'reference_many')
    .targetEntity(admin.getEntity('cases'))
    .targetField(nga.field('title'))
```
The correct requests are triggered in my case `/cases/:id`, and I know the filed `title` is present in every one of those response (I've tried various other fields too), but I'm getting the javascript error:
<img width="1127" alt="screen shot 2016-02-11 at 2 21 37 am" src="https://cloud.githubusercontent.com/assets/4655439/12967448/e14eb5e2-d066-11e5-8e4f-065fd102df00.png">
Resulting in:
<img width="648" alt="screen shot 2016-02-11 at 2 27 46 am" src="https://cloud.githubusercontent.com/assets/4655439/12967477/1aa92d36-d067-11e5-9396-e54346f66f70.png">

**Comment by fzaninotto** [comment]
@ajarbol are you using the master branch, or the latest tagged version?

**Comment by ajarbol** [comment]
@fzaninotto I've built from source on the `master` branch and I'm still seeing this error, thank you for your time.

**Comment by shanika** [comment]
+1 having the same issue

**Comment by oleksiy-unity3d** [comment]
I just had exactly the same problem, and it turned out it was caused by a type mismatch.

The list of reference-able items had ids as strings, while the list of references had ints.

I suppose that happens because ids are compared with `===`, and it's fine, but a warning in debug mode would have been useful.

**Comment by Kmaschta** [comment]
Thank you all for your feedback.
Feel free to reopen the issue you face it again with the master version, I close it for now.
