### ISSUE TITLE
Can't remove element in embedded_list.

### ISSUE THREAD

**Issue by cloudsix** [marmelab/ng-admin#818]
I can add and save and view the element in embedded_list.
but Remove button is not clickable.

1. b6b583c6fd99e5f9059954fde2a37ab59f5d0d97 in master from source.
2. I did not use my own build file but build file in source.
3. My codes are below.

config
```
    nga.field('pages', 'embedded_list'
        .targetFields([
            nga.field('image_link_source_link')
        ]),
```

mongodb database
```
  pages: [
    {
      image_link_source_link: "ddddddddddddd",
      _id: ObjectId("56569d0ae1175cd39c690653")
    }
  ],
```

![screenshot](https://cloud.githubusercontent.com/assets/5927326/11415978/db5f66dc-944c-11e5-8d49-9d921c696cf4.png)

**Comment by jontonsoup** [comment]
@cloudsix I'm getting this error as well -- did you find a solution to it?

**Comment by fzaninotto** [comment]
Is there an error in the JS console that you could paste here?

**Comment by cloudsix** [comment]
Sorry, I can't figure it out all of the detail. I forgot it because it was long long ago. And we dropped the project and source codes.

But the problem was layout exactly. Because other element overlap on that.  
I have to change css and rebuild the source. And Layout is in desolder but I can click it.

**Comment by jontonsoup** [comment]
@cloudsix Thanks! That was the issue

**Comment by jontonsoup** [comment]
@fzaninotto it seems like there is a bug in terms of layout overlap. 

<img width="914" alt="screen shot 2016-02-09 at 12 29 42 pm" src="https://cloud.githubusercontent.com/assets/845636/12924596/e2ffd41e-cf28-11e5-99bb-e8a2dbddc51c.png">

**Comment by jontonsoup** [comment]
@fzaninotto Thanks for the quick turnaround on this! Unfortunately, I'm still getting the overlap error (which prevents me from clicking the remove button). 

```
      #row-name{
        width: 80%;
      }
```

Fixes this, but It's a hack.

**Comment by fzaninotto** [comment]
I didn’t update the built files. I’ve just pushed a new version, can you try again?

**Comment by ajarbol** [comment]
This is also something I'm seeing, and I just used the latest build.
It seems the form-group is overlapping the button, any known work-arounds?
<img width="911" alt="screen shot 2016-02-11 at 2 03 09 am" src="https://cloud.githubusercontent.com/assets/4655439/12967078/b6541498-d063-11e5-810f-c5ffa3ddd548.png">

**Comment by fzaninotto** [comment]
Weird, my patched normally fixed the problem. Needs further inquiry.

**Comment by ajarbol** [comment]
@fzaninotto thanks for your quick response, it seems https://github.com/marmelab/ng-admin/commit/2b0ae16d8d4db5049b0f78c4220826437805a201did fix the problem, but the files we not built so I was still using the old changes. You may close this issue, I have nothing further.

**Comment by jontonsoup** [comment]
@fzaninotto I'm including from master and it still has not fixed my issue. The only thing that fixes my issue is the width: 80%. 

```
    script(src='https://rawgit.com/marmelab/ng-admin/master/build/ng-admin.min.js')
```

**Comment by Phocea** [comment]
Hello, same problem has @jontonsoup , building from master and the problem is still there. I double check and the patch is present

**Comment by Phocea** [comment]
Further note.
The fix is not yet included in the built ng-admin/build/ng-admin.min.css . this may be the problem ?

**Comment by ajarbol** [comment]
@Phocea @jontonsoup to consume the fix you must build the files from source.

**Comment by Phocea** [comment]
@ajarbol Yes I get this and this why I pointed it out. Shouldn't those file have also been updated on the MAIN build. @fzaninotto updated the js build file but not the css one. This would save confusion.

**Comment by jontonsoup** [comment]
@ajarbol unfortunately, I can't build from source and include it in my project because of this issue: https://github.com/marmelab/ng-admin/issues/880. 

I'm currently pulling from rawgit.com, but would love a proper CDN. https://github.com/marmelab/ng-admin/issues/931

**Comment by fzaninotto** [comment]
Can you try #932 and report here if it fixes the issue?

**Comment by Phocea** [comment]
Hello @fzaninotto . sorry for the late feedback (was on vacation). All good after the build css patch. thanks for the quick turnaround
